bayesian_gnn:
  input_dim: 512
  hidden_dim: 1024
  output_dim: 2
  n_hidden: 1
  epochs: 500
  lr: 1e-5
  weight_decay: 0.01
  dropout: 0.5
  batch_size: 32
  num_workers: 4
  n_neigh_train: 16
  n_neigh_full: 16
  graph_mode: knn
  lbl_train_frac: 0.8
  sample: false
  loss: "nll_balanced"
  best_model_metric: "best_hm"
  dataset: "CrisisMMD"
  imageft: "maxvit"
  textft: "mpnet"
  fusion: "early"
  reduction: autoenc
  autoenc: base_ae
  group: gnn
  num_test_inference_run: 10
  num_inference_run: 100

bayesian_gnn_clip:
  base: bayesian_gnn
  input_dim: 1024
  hidden_dim: 2048
  imageft: "clip"
  textft: "clip"
  reduction: null

bayesian_mlp:
  base: bayesian_gnn
  group: mlp

bayesian_hybrid:
  base: bayesian_gnn
  group: hybrid

bayesian_gnn_sim:
  base: bayesian_gnn
  graph_mode: sim

bayesian_gnn_sim_conn:
  base: bayesian_gnn
  graph_mode: sim-connected

bayesian_mlp_clip:
  base: bayesian_gnn_clip
  group: mlp

bayesian_hybrid_clip:
  base: bayesian_gnn_clip
  group: hybrid